# ROS2 Parameters for ORB-SLAM3 with USB Camera

orb_slam3_mono:
  ros__parameters:
    # ORB-SLAM3 Configuration Files
    vocabulary_path: "/home/cesar/Projects/ORB_SLAM3/Vocabulary/ORBvoc.txt"
    settings_path: "/home/cesar/Projects/ORB_SLAM3/ROS2/config/webcam.yaml"
    use_viewer: true
    
    # Topic names - USB camera typical topics
    image_topic: "/camera1/image_raw"
    pose_topic: "orb_slam3/camera_pose"
    path_topic: "orb_slam3/camera_path"
    
    # Frame IDs
    world_frame_id: "world"
    camera_frame_id: "usb_cam"
    
    # Publisher settings
    queue_size: 10
    publish_tf: true
