%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration (EXAMPLE - calibrate your camera!)
Camera.fx: 500.0
Camera.fy: 500.0
Camera.cx: 320.0
Camera.cy: 240.0

# Distortion coefficients: (k1, k2, p1, p2, k3)
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

Camera.width: 640
Camera.height: 480
Camera.fps: 30.0
Camera.RGB: 0

#--------------------------------------------------------------------------------------------
# RGB-D Parameters (required when use_depth=true)
#--------------------------------------------------------------------------------------------
# Camera baseline times fx (for stereo/RGB-D). Set to 0 for monocular
Camera.bf: 40.0

# Close/Far threshold. Baseline times
ThDepth: 40.0

# Depth map scale factor (convert depth values to meters)
# For DepthAnything output (normalized 0-1), use 1.0
# For typical depth cameras: 1000.0 (if depth is in mm), 5000.0 (TUM/KITTI format)
DepthMapFactor: 1.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1000
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
